# Generated by Django 5.1.4 on 2025-01-17 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_francais', models.CharField(max_length=255)),
                ('name_arabe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('request_type', models.CharField(choices=[('Reclamation', 'Reclamation'), ('Suggestion', 'Suggestion')], max_length=15)),
                ('domaine', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Santé', 'Santé'), ('Education', 'Education'), ('Propriété', 'Propriété'), ('Transport', 'Transport'), ('Eclairage public', 'Eclairage public'), ('Autre', 'Autre')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='demande.municipalite')),
            ],
        ),
    ]
