# Generated by Django 5.1.4 on 2025-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_demande_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('non traité', 'Non traité'), ('en cours', 'En cours'), ('traité', 'Traité')], default='non traité', max_length=20),
        ),
    ]
