# Generated by Django 5.1.4 on 2025-01-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_demande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalite',
            name='name_arabe',
        ),
    ]
